[package]
name = "hyprland-qmk-window-notifier"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
qmk_notifier = { package = "qmk_notifier", git = "https://github.com/dabstractor/qmk_notifier.git", branch = "main" }
hyprland = "0.4.0-beta.2"
